### ISSUE TITLE
About Paper

### ISSUE THREAD

**Issue by 123456789asdfjkl** [LMD0311/DAPT#1]
Hi! Thank you for your great work!  I want to know where the paper can be downloaded.

**Comment by LMD0311** [comment]
Thank you for your interest in our work! We will submit the paper to arXiv in a few days and update the link in the repository as soon as possible.

**Comment by LMD0311** [comment]
> Hi! Thank you for your great work! I want to know where the paper can be downloaded.

Hi! The paper can be found [here](https://arxiv.org/abs/2403.01439). Thank you for your interest!
