### ISSUE TITLE
About Pretrain pointmae Checkpoint

### ISSUE THREAD

**Issue by 123456789asdfjkl** [LMD0311/DAPT#3]
Hi! Thank you for your great work! I want to know where is the pointmae checkpoint. I noticed that the pos embedding in your implementation is different from the original PointMAE. May I ask if you would like to retrain it?

**Comment by LMD0311** [comment]
Thanks for your interest!

You can download the Point-MAE checkpoint from the Point-MAE ([here](https://github.com/Pang-Yatian/Point-MAE)) or IDPT ([here](https://github.com/zyh16143998882/ICCV23-IDPT)) repositories.

We did not re-pre-train the model.
