### ISSUE TITLE
About PointBert

### ISSUE THREAD

**Issue by 123456789asdfjkl** [LMD0311/DAPT#4]
Hi! Thank you for your great work! I want to know how your pointbert classification header is implemented.

![image](https://github.com/LMD0311/DAPT/assets/45223476/faaf4c25-0119-4a92-9ba2-a84384a2b4b4)

or

![image](https://github.com/LMD0311/DAPT/assets/45223476/6f6aed07-0233-422a-b2ce-6822fd354393)

**Comment by LMD0311** [comment]
We reported the results with Point-MAE's head.

**Comment by 123456789asdfjkl** [comment]
Thank you for your answer! I would like to know if your npoints in pointbert are also set to 2048 like pointmae

**Comment by LMD0311** [comment]
Yes. Could you send me an email (xzhou03@hust.edu.cn) for WeChat contact?
