### ISSUE TITLE
Question about fewshot

### ISSUE THREAD

**Issue by zsc000722** [LMD0311/DAPT#5]
Hi! Thanks for your great work. I'm wondering if there are some special settings while you were doing the ModelNet fewshot experiment, for I cannot reproduce the results you offered in the paper. Could you please tell me some probable reasons? And if possible can you share the config.yaml file of fewshot experiments? Best wishes!

**Comment by LMD0311** [comment]
Thanks for your interest!

It is common to obtain varied outcomes on diverse machines, stemming from the interplay of instability and randomness. We suggest experimenting with various random seeds and opting for the best result.
