### ISSUE TITLE
Segmentation Experiment on Shapenet

### ISSUE THREAD

**Issue by HazardFY** [LMD0311/DAPT#6]
Hi! Thank you for sharing your advanced work! 
I noticed that you mentioned using a decoder similar to PointMAE for your experiments and treating the extra Internal Prompt generated by the adapter as global information. Could you provide detailed code? Is the structure similar to that in IDPT(https://github.com/zyh16143998882/ICCV23-IDPT/tree/main/segmentation)?

**Comment by LMD0311** [comment]
Apologies for the late response. The structure is similar to that in IDPT, but the code is not organized yet. You may send me an [email](mailto:xzhou03@hust.edu.cn) for the organized version if needed.
